version: '2.1'
services:
  amore:
    build: .
    env_file:
      - postgres_config.env
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    command: ./start.sh
    volumes:
      - amore_log:/usr/app/data

  db:
    image: postgres:latest
    env_file:
      - postgres_config.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - amore_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  amore_db:
  amore_log: